cache:
  directories:
  - node_modules
language: node_js
script:
- yarn lint
- if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
  yarn semantic-release; fi
node_js:
- lts/*
env:
  global:
  - secure: PMxcU6AXZQ3JSSjQD5wgMdtsu/n1+Nh0iXLDNFuqoxrUtBEpd/jTgadAScxuSMK+nC788i+B/+qBF6C3nVQbCv8zOpqZL09t7ueYE6zoT8drwYw09sGPmP0E39BgP5WHfM+JFRLWKWTi0/edh8pBzR7zLAcL4wTvoMNpKVyFESfA86uZu1MN1D/dQ3oBllV8IugQ/u+FBPmDmTdY/gxPhDYXKlkm2u9QofontlZLOsTq2ewIVMtyfqphiwliFROr1WFO2rq8ZRmoQBAsy2liuNwA0NK6vbW2nLSbkGL2jtKXK7209iuGOw9EIDS51kT7f0FaI5AtkqYNtRcWmNSKuavhEjVP2tMQJ5wzPxQ+hypPSw1gqYb3Qd+/m4veOlCB91mZPOVQD7RbNIvVLcZa49BFm8EqFAZY2/7xEsb9ZJzA/UHj2zcLOdNdXmC6+QnSUOTVSgkN3VwrxTHFU9XpfmAAnFIFZXlGj1o3FYEVzfjCUTQR8sU6GXamtK+fGVvpKwJmaKWa+TZ59dfmAPcyksRiqBxLgakthd7D2w+ieoGsWyvkA+chHTUyAv4SZQ977f6Bp9cUD238Xe/d2XlqfQOBpRBqoBGJy3JQd6BauEF8OTlLKA/leWAKlKnycNcw3ms7ZqMUFTZm+2TT5KM/xD0XnjvGwHUN9Efy70p64r4=
  - secure: DHeWuBtA9XdwUA768Tva8h8NqGVskihzNGSD/KRakttAvQ/M6uEjh73mQRscDoNhYSWN6Ws7Av1nVfzYVEm6tmBiue47XlYAv29IMNr0UAPn/blWkvOGyeeFGvVXjRzcNd1vcXSaPJPF8IsR2WDzdPBzUBvDlyNv17u73/wtMeY7akPh5UvptwLj9ihMFupEXE/3P4/IHalddPaLqdCfl/42mbur36Yt3nropM0cMzqXfPssFDHW1Fjz9kL0YVY00vv9TClnEWqpxNWP/Ny8wIXbjQ/TM59Z3vu7eMlsgrM+V8LI2vgy8IHHq3v1kPpkWe8mp8WzVapIl7oY+OumayjeYvdHA2IbUqa9VciSmP43bPpwvnxsVfSYeLYc2mo2ZBZesOiDnVlgdtr3LxqEBCoNipz7z+nnbnerOs85B3M8MuR2Dc+hfHPWSNMojrEgvoBaDbP1HrHaz1q4ePBD6UswUNIyNdzg0aWXrZQ8de1iH6fIjPRMhqsTyEc8nOFP7gbJZgdsaOKckQcpQm8CBjoH+0WVF3K6G5B/MiMSj4bjgLwNOcK1mQj16f7kEe33IaYbeR6vi69l6Ab3DwBkWjg4YlbE01dNTS65oszbHlP7O6K2gS0nJjda7QqxHpiYJj412k5AKlKUswzwauHP5cn6jiS1Ch0D+wfzGkHBJA4=
